version: '3'
services:
  backend:
    container_name: api.moki.codes
    build: .
    expose:
      - ${BACKEND_CONTAINER_PORT}
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - proxy
      - api
  redis:
    container_name: api.moki.codes_database
    build:
      context: .
      dockerfile: Dockerfile-redis
    expose:
      - ${REDIS_CONTAINER_PORT}
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - api

volumes:
  redis-data:

networks:
  proxy:
    external:
      name: nginx-proxy
  api:
